Teacup: clock.c File Reference
clock.c File Reference
Do stuff periodically.
#include "clock.h"
#include "pinio.h"
#include "sersendf.h"
#include "dda_queue.h"
#include "watchdog.h"
#include "temp.h"
#include "timer.h"
#include "debug.h"
#include "heater.h"
#include "serial.h"
Functions
void clock_250ms ()
do stuff every 1/4 second
void clock_10ms ()
do stuff every 10 milliseconds
Detailed Description
Do stuff periodically.
Function Documentation
void clock_10ms (void)
do stuff every 10 milliseconds
call from ifclock(CLOCK_FLAG_10MS) in busy loops
Referenced by main(), process_gcode_command(), and queue_wait().
void clock_250ms (void)
do stuff every 1/4 second
called from clock_10ms(), do not call directly
Referenced by clock_10ms().