Teacup: clock.h File Reference
clock.h File Reference
Functions
void clock_250ms (void)
do stuff every 1/4 second
void clock_10ms (void)
do stuff every 10 milliseconds
Function Documentation
void clock_10ms (void)
do stuff every 10 milliseconds
call from ifclock(CLOCK_FLAG_10MS) in busy loops
Referenced by main(), process_gcode_command(), and queue_wait().
void clock_250ms (void)
do stuff every 1/4 second
called from clock_10ms(), do not call directly
Referenced by clock_10ms().