Teacup: dda_queue.h File Reference
dda_queue.h File Reference
#include "dda.h"
Functions
uint8_t queue_full (void)
check if the queue is completely full
uint8_t queue_empty (void)
check if the queue is completely empty
void queue_step (void)
Take a step or go to the next move.
void enqueue (TARGET *t)
add a move to the movebuffer
void next_move (void) __attribute__((hot))
go to the next move.
void print_queue (void)
DEBUG - print queue.
void queue_flush (void)
dump queue for emergency stop.
void queue_wait (void)
waits for a space in the queue to become available
Variables
uint8_t mb_head
movebuffer head pointer. Points to the last move in the queue.
uint8_t mb_tail
movebuffer tail pointer. Points to the currently executing move
DDA movebuffer [MOVEBUFFER_SIZE]
Function Documentation
void enqueue (TARGET * t)
add a move to the movebuffer
Note:
this function waits for space to be available if necessary, check queue_full() first if waiting is a problem
Referenced by home_x_positive(), home_y_positive(), home_z_positive(), and process_gcode_command().
void next_move (void)
go to the next move.
be aware that this is sometimes called from interrupt context, sometimes not.
Referenced by enqueue(), and queue_step().
void print_queue (void)
DEBUG - print queue.
Qt/hs format, t is tail, h is head, s is F/full, E/empty or neither
Referenced by clock_250ms(), and process_gcode_command().
uint8_t queue_empty (void)
check if the queue is completely empty
Referenced by next_move(), print_queue(), and queue_wait().
void queue_flush (void)
dump queue for emergency stop.
Todo:
effect on startpoint/current_position is undefined!
Referenced by process_gcode_command().
uint8_t queue_full (void)
check if the queue is completely full
Referenced by enqueue(), main(), and print_queue().
void queue_step (void)
Take a step or go to the next move.
void queue_wait (void)
waits for a space in the queue to become available
Referenced by home(), and process_gcode_command().
Variable Documentation
uint8_t mb_head
movebuffer head pointer. Points to the last move in the queue.
Referenced by enqueue(), print_queue(), queue_empty(), queue_flush(), and queue_full().
uint8_t mb_tail
movebuffer tail pointer. Points to the currently executing move
Referenced by clock_250ms(), enqueue(), next_move(), print_queue(), process_gcode_command(), queue_empty(), queue_flush(), queue_full(), and queue_step().
DDA movebuffer[MOVEBUFFER_SIZE]
Referenced by clock_250ms(), enqueue(), next_move(), process_gcode_command(), queue_empty(), queue_flush(), and queue_step().