Teacup: delay.c File Reference
delay.c File Reference
Delay routines.
#include "delay.h"
#include "watchdog.h"
Functions
void delay (uint32_t delay)
delay microseconds
void delay_ms (uint32_t delay)
delay milliseconds
void delayMicrosecondsInterruptible (uint16_t us)
internal- wait for up to 65.5ms using a busy loop
Detailed Description
Delay routines.
Function Documentation
void delay (uint32_t delay)
delay microseconds
Parameters:
delay time to wait in microseconds
Referenced by enqueue(), home_x_negative(), home_x_positive(), home_y_negative(), home_y_positive(), home_z_negative(), home_z_positive(), lcd_init(), and temp_sensor_tick().
void delay_ms (uint32_t delay)
delay milliseconds
Parameters:
delay time to wait in milliseconds
Referenced by process_gcode_command().
void delayMicrosecondsInterruptible (uint16_t us)
internal- wait for up to 65.5ms using a busy loop
Parameters:
us time to wait in microseconds
Referenced by delay(), and delay_ms().