Teacup: home.h File Reference
home.h File Reference
Functions
void home (void)
home all 3 axes
void home_x_negative (void)
find X MIN endstop
void home_x_positive (void)
find X_MAX endstop
void home_y_negative (void)
fund Y MIN endstop
void home_y_positive (void)
find Y MAX endstop
void home_z_negative (void)
find Z MIN endstop
void home_z_positive (void)
find Z MAX endstop
Function Documentation
void home (void)
home all 3 axes
void home_x_negative (void)
find X MIN endstop
Referenced by home(), and process_gcode_command().
void home_x_positive (void)
find X_MAX endstop
Referenced by home(), and process_gcode_command().
void home_y_negative (void)
fund Y MIN endstop
Referenced by home(), and process_gcode_command().
void home_y_positive (void)
find Y MAX endstop
Referenced by home(), and process_gcode_command().
void home_z_negative (void)
find Z MIN endstop
Referenced by home(), and process_gcode_command().
void home_z_positive (void)
find Z MAX endstop
Referenced by home(), and process_gcode_command().