Teacup: intercom.h File Reference
intercom.h File Reference
#include <stdint.h>
#include "config.h"
Data Structures
struct intercom_packet_t
intercom packet structure, both tx and rx
union intercom_packet
this allows us to fill the packet struct, then pass it to something that expects an array of bytes
Defines
#define enable_transmit() do { WRITE(TX_ENABLE_PIN,1); UCSR0B &= ~MASK(RXEN0); } while(0)
#define disable_transmit() do { WRITE(TX_ENABLE_PIN,0); UCSR0B &= ~(MASK(TXCIE0) | MASK(UDRIE0)); UCSR0B |= MASK(RXEN0); } while(0)
#define FLAG_RX_IN_PROGRESS 1
#define FLAG_TX_IN_PROGRESS 2
#define FLAG_NEW_RX 4
#define FLAG_TX_FINISHED 8
Enumerations
enum { ERROR_BAD_CRC }
list of error codes, not many so far...
Functions
void intercom_init (void)
initialise serial subsystem
void send_temperature (uint8_t index, uint16_t temperature)
if host, send target temperature to extruder if extruder, send actual temperature to host
uint16_t read_temperature (uint8_t index)
if host, read actual temperature from extruder if extruder, read target temperature from host
void set_dio (uint8_t index, uint8_t value)
if host, set DIOs on extruder controller if extruder, report DIO state
uint8_t get_dio (uint8_t index)
if host, read extruder DIO inputs if extruder, set DIO outputs
void set_err (uint8_t err)
set error code to send to other end
uint8_t get_err (void)
get error code sent from other end
void start_send (void)
if host, send packet to extruder if extruder, return packet to host
Variables
enum { ... } err_codes
intercom_packet tx
intercom_packet rx
volatile uint8_t intercom_flags
Define Documentation
#define disable_transmit () do { WRITE(TX_ENABLE_PIN,0); UCSR0B &= ~(MASK(TXCIE0) | MASK(UDRIE0)); UCSR0B |= MASK(RXEN0); } while(0)
Referenced by io_init().
#define enable_transmit () do { WRITE(TX_ENABLE_PIN,1); UCSR0B &= ~MASK(RXEN0); } while(0)
#define FLAG_NEW_RX 4
Referenced by main().
#define FLAG_RX_IN_PROGRESS 1
#define FLAG_TX_FINISHED 8
#define FLAG_TX_IN_PROGRESS 2
Enumeration Type Documentation
anonymous enum
list of error codes, not many so far...
Enumerator:
ERROR_BAD_CRC
Function Documentation
uint8_t get_dio (uint8_t index)
if host, read extruder DIO inputs if extruder, set DIO outputs
uint8_t get_err (void)
get error code sent from other end
void intercom_init (void)
initialise serial subsystem
Referenced by init(), and temp_init().
uint16_t read_temperature (uint8_t index)
if host, read actual temperature from extruder if extruder, read target temperature from host
Referenced by main(), and temp_sensor_tick().
void send_temperature (uint8_t index, uint16_t temperature)
if host, send target temperature to extruder if extruder, send actual temperature to host
Referenced by main(), temp_init(), and temp_set().
void set_dio (uint8_t index, uint8_t value)
if host, set DIOs on extruder controller if extruder, report DIO state
void set_err (uint8_t err)
set error code to send to other end
void start_send (void)
if host, send packet to extruder if extruder, return packet to host
Referenced by clock_250ms(), and main().
Variable Documentation
enum { ... } err_codes
volatile uint8_t intercom_flags
Referenced by main().
intercom_packet rx
Referenced by main().
intercom_packet tx