Teacup: serial.h File Reference
serial.h File Reference
#include <stdint.h>
#include <avr/io.h>
#include <avr/pgmspace.h>
Functions
void serial_init (void)
initialise serial subsystem
uint8_t serial_rxchars (void)
uint8_t serial_popchar (void)
void serial_writechar (uint8_t data)
void serial_writeblock (void *data, int datalen)
void serial_writestr (uint8_t *data)
void serial_writeblock_P (PGM_P data, int datalen)
void serial_writestr_P (PGM_P data)
Function Documentation
void serial_init (void)
initialise serial subsystem
set up baud generator and interrupts, clear buffers
Referenced by init().
uint8_t serial_popchar (void)
Referenced by main().
uint8_t serial_rxchars (void)
Referenced by main().
void serial_writeblock (void * data, int datalen)
void serial_writeblock_P (PGM_P data, int datalen)
void serial_writechar (uint8_t data)
Referenced by clock_250ms(), dda_create(), gcode_parse_char(), request_resend(), sersendf_P(), serwrite_hex4(), serwrite_int32(), and serwrite_uint32().
void serial_writestr (uint8_t * data)
void serial_writestr_P (PGM_P data)
Referenced by dda_create(), gcode_parse_char(), init(), next_move(), process_gcode_command(), queue_step(), request_resend(), and sersendf_P().