#ifndef F_CPU
 #define F_CPU 20000000UL
#endif
#define MOTHERBOARD
#define STEPS_PER_M_X (STEPS_PER_MM * 1000)
#define STEPS_PER_M_Y (STEPS_PER_MM * 1000)
#define STEPS_PER_M_Z (STEPS_PER_MM * 1000)
#define STEPS_PER_M_E (STEPS_PER_MM * 1000)
#define MAXIMUM_FEEDRATE_X 1000000
#define MAXIMUM_FEEDRATE_Y 1000000
#define MAXIMUM_FEEDRATE_Z 1000000
#define MAXIMUM_FEEDRATE_E 1000000
#define SEARCH_FEEDRATE_X 150
#define SEARCH_FEEDRATE_Y 150
#define SEARCH_FEEDRATE_Z 30
#define SLOW_HOMING
#define E_STARTSTOP_STEPS 289


#define MAX_JERK_X 20
#define MAX_JERK_Y 20
#define MAX_JERK_Z 0
#define MAX_JERK_E 20

#include "arduino.h"
#define USE_INTERNAL_PULLUPS
#define TEMP_HYSTERESIS 20
#define TEMP_RESIDENCY_TIME 60
#define TEMP_EWMA 1.0
#define TEMP_THERMISTOR
#ifndef DEFINE_TEMP_SENSOR
 #define DEFINE_TEMP_SENSOR(...)
#endif
DEFINE_TEMP_SENSOR(extruder, TT_THERMISTOR, AIO1, THERMISTOR_EXTRUDER)
DEFINE_TEMP_SENSOR(bed, TT_THERMISTOR, AIO2, THERMISTOR_BED)
#ifndef DEFINE_HEATER
 #define DEFINE_HEATER(...)
#endif

DEFINE_HEATER(extruder, DIO4, 1)
DEFINE_HEATER(bed, DIO3, 1)
#define HEATER_EXTRUDER HEATER_extruder
#define HEATER_BED HEATER_bed
#define BAUD 115200
#define EECONFIG
#define MOVEBUFFER_SIZE 8
#define REFERENCE REFERENCE_AVCC
#define STEP_INTERRUPT_INTERRUPTIBLE 1
#define TH_COUNT 8
#define PID_SCALE 1024L
#define ENDSTOP_STEPS 4
